sudo: false
language: php
dist: trusty

php:
  - 7.2

env:
  - MONGO_VERSION=stable

services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mediainfo
      - libav-tools
      - libavcodec-extra-54

before_script:
  - pecl install -f mongodb-${MONGO_VERSION}
  - composer self-update
  - php -i
  - npm install -g pa11y
  - pa11y -V
  - composer -V
  - composer install


script:
    - find src -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - php app/console lint:yaml src
    - php app/console lint:yaml app
    - php app/console lint:twig src
    - php app/console lint:twig app
    - ./bin/travis_checks/check_var_dumps
    - php bin/php-cs-fixer.phar fix src --rules=@Symfony --dry-run -v
    - php bin/phpunit -c app
    - php app/console doctrine:mongodb:schema:create
    - php app/console pumukit:init:repo all --force
#    - php app/console pumukit:init:example  --force
    - php app/console server:start --env=prod
    - pa11y -c .pa11y.json http://localhost:8000/
    - pa11y -c .pa11y.json http://localhost:8000/series/channel/1.html
    - pa11y -c .pa11y.json http://localhost:8000/latestuploads
    - pa11y -c .pa11y.json http://localhost:8000/searchmultimediaobjects
    - pa11y -c .pa11y.json http://localhost:8000/searchseries
#    - pa11y -c .pa11y.json http://localhost:8000/live/595b77640fd60c42008b4567
    - pa11y -c .pa11y.json http://localhost:8000/mediateca
    - pa11y -c .pa11y.json http://localhost:8000/categories
#    - pa11y -c .pa11y.json http://localhost:8000/video/59269ab79833a041008b4576
#    - pa11y -c .pa11y.json http://localhost:8000/series/5925a5519833a043008b456c
    - php app/console server:stop
