imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: parameters_deploy.yml, ignore_errors: true }
    - { resource: encoder.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        pumukit2_info: "%pumukit2.info%"
        locales:       "%pumukit2.locales%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# MongoDB configuration
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: "%mongodb_database%"
    auto_generate_hydrator_classes: true
    auto_generate_proxy_classes: true
    document_managers:
        default:
            auto_mapping: true
            filters:
                frontend:
                    class:     Pumukit\CoreBundle\Filter\WebTVFilter
                    enabled:   false
                channel:
                    class:     Pumukit\CoreBundle\Filter\ChannelFilter
                    enabled:   false
                backoffice:
                    class:     Pumukit\CoreBundle\Filter\AdminFilter
                    enabled:   false
                personal:
                    class:     Pumukit\CoreBundle\Filter\PersonalFilter
                    enabled:   false


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Pumukit\SchemaBundle\Document\User

# MobileDetectBundle Configuration
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

vipx_bot_detect:
    metadata_file: extended.yml
