pumukitnewadmin_event_index:
    pattern: /
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:index
        _sylius:
            filterable: true

pumukitnewadmin_event_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:create
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_update:
    pattern: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:update
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:batchDelete
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:delete
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:show

pumukitnewadmin_event_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:list
        _sylius:
            filterable: true

pumukitnewadmin_event_updatesession:
    pattern: /updatesession
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:LegacyEvent:updateSession