pumukitnewadmin_eventpic_create:
    pattern: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.eventpic:createAction

pumukitnewadmin_eventpic_update:
    pattern: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.eventpic:updateAction

pumukitnewadmin_eventpic_upload:
    pattern: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.eventpic:uploadAction

pumukitnewadmin_eventpic_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.eventpic:deleteAction
