pumukitnewadmin_live_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Live:index
        _sylius:
            filterable: true

pumukitnewadmin_live_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Live:create
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_update:
    pattern: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Live:update
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Live:batchDelete
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Live:delete
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Live:copy
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Live:show

pumukitnewadmin_live_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Live:list
        _sylius:
            filterable: true
