pumukitnewadmin_mms_index:
    pattern: /series
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_mms_create:
    pattern: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:createAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_edit:
    pattern: /{id}/edit
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:editAction

pumukitnewadmin_mms_links:
    pattern: /{id}/links
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:linksAction

pumukitnewadmin_mms_update_meta:
    pattern: /{id}/update/meta
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:updatemetaAction

pumukitnewadmin_mms_update_pub:
    pattern: /{id}/update/pub
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:updatepubAction

pumukitnewadmin_mms_batch_delete:
    pattern: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.mms:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.mms:deleteAction

pumukitnewadmin_mms_generate_magic_url:
    pattern: /{id}/generatemagic
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:generateMagicUrlAction

pumukitnewadmin_mms_clone:
    pattern: /{id}/clone
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:cloneAction

pumukitnewadmin_mms_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:copyAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_show:
    pattern: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:showAction

pumukitnewadmin_mms_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:upAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:downAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:topAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:bottomAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mms_addtag:
    pattern: /{id}/addtag/
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:addTagAction
        _sylius:
            redirect: pumukitnewadmin_mms_edit

pumukitnewadmin_mms_deletetag:
    pattern: /{id}/deletetag/{tagId}
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.mms:deleteTagAction

pumukitnewadmin_mms_getchildrentag:
    pattern: /{id}/getchildrentag/
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:getChildrenTagAction

pumukitnewadmin_mms_searchtag:
    pattern: /search/{search_text}
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:searchTagAction
        search_text:

pumukitnewadmin_mms_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:listAction

pumukitnewadmin_mms_status:
    pattern: /{id}/status
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:statusAction

pumukitnewadmin_mms_invert_announce:
    pattern: /invertannounce
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:invertAnnounceAction

pumukitnewadmin_mms_cut:
    pattern: /cut
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:cutAction

pumukitnewadmin_mms_paste:
    pattern: /paste
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:pasteAction

pumukitnewadmin_mms_reorder:
    pattern: /reorder
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:reorderAction

pumukitnewadmin_mms_reloadtags:
    pattern: /reloadtags
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:reloadTagsAction

pumukitnewadmin_mms_sync_tags:
    pattern: /synctags
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:syncTagsAction

pumukitnewadmin_mms_editgroups:
    pattern: /editgroups
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:editGroupsAction

pumukitnewadmin_mms_updategroups:
    pattern: /updategroups
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:updateGroupsAction

pumukitnewadmin_mms_getgroups:
    pattern: /getgroups
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:getGroupsAction

pumukitnewadmin_mms_broadcast_info:
    pattern: /{id}/broadcastinfo
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:getBroadcastInfoAction

pumukitnewadmin_mms_updatebroadcast:
    pattern: /{id}/updatebroadcast
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:updateBroadcastAction

pumukitnewadmin_mms_user_last_relation:
    pattern: /user/lastrelation
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.mms:userLastRelationAction

pumukitnewadmin_mms_listproperties:
    pattern: /{id}/listproperties
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:listPropertiesAction

pumukitnewadmin_mms_modal_preview:
    pattern: /{id}/modalpreview
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.mms:modalPreviewAction
