pumukitnewadmin_permissionprofile_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:index
        _sylius:
            filterable: true

pumukitnewadmin_permissionprofile_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:create
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:update
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:batchDelete
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:delete
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:list

pumukitnewadmin_permissionprofile_batch_update:
    pattern: /batchupdate
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:batchUpdate
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_export:
    pattern: /export
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PermissionProfile:exportPermissionProfiles