pumukitnewadmin_playlistmms_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:index
        filter: false
        _sylius:
            filterable: true

pumukitnewadmin_playlistmms_create:
    pattern: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:create
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_show:
    pattern: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:show
        filter: false

pumukitnewadmin_playlistmms_info:
    pattern: /{id}/info
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:info
        filter: false

pumukitnewadmin_playlistmms_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:up
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:down
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:top
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:bottom
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:list
        filter: false

pumukitnewadmin_playlistmms_cut:
    pattern: /cut
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:cut

pumukitnewadmin_playlistmms_paste:
    pattern: /paste
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:paste

pumukitnewadmin_playlistmms_reorder:
    pattern: /reorder
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:reorder

pumukitnewadmin_playlistmms_modal:
    pattern: /{id}/modal
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:modal

pumukitnewadmin_playlistmms_modal_mymmobjs:
    pattern: /{id}/modal_mymmobjs
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:modalMyMmobjs

pumukitnewadmin_playlistmms_modal_search:
    pattern: /modal_search
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:searchModal

pumukitnewadmin_playlistmms_modal_url:
    pattern: /modal_url
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:urlModal

pumukitnewadmin_playlistmms_batch_add:
    pattern: /{id}/add
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:addBatch

pumukitnewadmin_playlistmms_batch_delete:
    pattern: /{id}/delete
    methods: [GET, POST, DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:deleteBatch

pumukitnewadmin_playlistmms_modal_add:
    pattern: /modal
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:addModal

pumukitnewadmin_playlistmms_batch_add_to_several_playlist:
    pattern: /
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:addBatchToSeveralPlaylist

pumukitnewadmin_playlistmms_info:
    pattern: /{id}/links
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:PlaylistMultimediaObject:info
