pumukitnewadmin_role_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:Role:index
        _sylius:
            filterable: true
            sorting:
                rank: desc

pumukitnewadmin_role_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:create
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:update
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Role:batchDelete
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:Role:delete
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:copy
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:up
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:down
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:top
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:bottom
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:list

pumukitnewadmin_role_export:
    pattern: /export
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:Role:exportRoles