pumukitnewadmin_role_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.role:indexAction
        _sylius:
            filterable: true
            sorting:
                rank: desc

pumukitnewadmin_role_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:createAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:updateAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_batch_delete:
    pattern: /delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.role:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.role:deleteAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:copyAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_up:
    pattern: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:upAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_down:
    pattern: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:downAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_top:
    pattern: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:topAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_bottom:
    pattern: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:bottomAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:listAction

pumukitnewadmin_role_export:
    pattern: /export
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.role:exportRolesAction