pumukitnewadmin_seriestype_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:index
        _sylius:
            filterable: true

pumukitnewadmin_seriestype_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:create
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_update:
    pattern: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:update
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:batchDelete
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:delete
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_copy:
    pattern: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:copy
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_show:
    pattern: /{id}/show
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:show

pumukitnewadmin_seriestype_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:SeriesType:list
        _sylius:
            filterable: true
