pumukitnewadmin_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:User:index
        _sylius:
            filterable: true

pumukitnewadmin_user_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:User:create
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: PumukitNewAdminBundle:User:update
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:User:batchDelete
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: PumukitNewAdminBundle:User:delete
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: PumukitNewAdminBundle:User:list

pumukitnewadmin_user_promote:
    pattern: /promote
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:User:promote

pumukitnewadmin_user_editgroups:
    pattern: /editgroups
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:User:editGroups

pumukitnewadmin_user_updategroups:
    pattern: /updategroups
    methods: [POST]
    defaults:
        _controller: PumukitNewAdminBundle:User:updateGroups

pumukitnewadmin_user_getgroups:
    pattern: /getgroups
    methods: [GET]
    defaults:
        _controller: PumukitNewAdminBundle:User:getGroups