pumukitnewadmin_user_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.user:indexAction
        _sylius:
            filterable: true

pumukitnewadmin_user_create:
    pattern: /create
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.user:createAction
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: pumukitnewadmin.controller.user:updateAction
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_batch_delete:
    pattern: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.user:batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: pumukitnewadmin.controller.user:deleteAction
        _sylius:
            redirect: pumukitnewadmin_user_index

pumukitnewadmin_user_list:
    pattern: /list
    methods: [GET, POST]
    defaults:
        _controller: pumukitnewadmin.controller.user:listAction

pumukitnewadmin_user_promote:
    pattern: /promote
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.user:promoteAction

pumukitnewadmin_user_editgroups:
    pattern: /editgroups
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.user:editGroupsAction

pumukitnewadmin_user_updategroups:
    pattern: /updategroups
    methods: [POST]
    defaults:
        _controller: pumukitnewadmin.controller.user:updateGroupsAction

pumukitnewadmin_user_getgroups:
    pattern: /getgroups
    methods: [GET]
    defaults:
        _controller: pumukitnewadmin.controller.user:getGroupsAction