sylius_resource:
    resources:
        pumukitnewadmin.broadcast:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Broadcast
            classes:
                model: Pumukit\SchemaBundle\Document\Broadcast
                controller: Pumukit\NewAdminBundle\Controller\BroadcastController
        pumukitnewadmin.role:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Role
            classes:
                model: Pumukit\SchemaBundle\Document\Role
                controller: Pumukit\NewAdminBundle\Controller\RoleController
        pumukitnewadmin.user:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:User
            classes:
                model: Pumukit\SchemaBundle\Document\User
                controller: Pumukit\NewAdminBundle\Controller\UserController
        pumukitnewadmin.person:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Person
            classes:
                model: Pumukit\SchemaBundle\Document\Person
                controller: Pumukit\NewAdminBundle\Controller\PersonController
        pumukitnewadmin.series:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Series
            classes:
                model: Pumukit\SchemaBundle\Document\Series
                controller: Pumukit\NewAdminBundle\Controller\SeriesController
        pumukitnewadmin.playlist:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Playlist
            classes:
                model: Pumukit\SchemaBundle\Document\Series
                controller: Pumukit\NewAdminBundle\Controller\PlaylistController
        pumukitnewadmin.collection:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Playlist
            classes:
                model: Pumukit\SchemaBundle\Document\Series
                controller: Pumukit\NewAdminBundle\Controller\CollectionController
        pumukitnewadmin.mmtemplate:
            driver: doctrine/mongodb-odm
            templates: PumukitnewadminBundle:MultimediaObjectTemplate
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectTemplateController
        pumukitnewadmin.mms:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:MultimediaObject
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectController
        pumukitnewadmin.playlistmms:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:PlaylistMultimediaObject
            classes:
                model: Pumukit\SchemaBundle\Document\MultimediaObject
                controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController
        pumukitnewadmin.seriespic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\SchemaBundle\Document\Pic
                controller: Pumukit\NewAdminBundle\Controller\SeriesPicController
        pumukitnewadmin.mmspic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\SchemaBundle\Document\Pic
                controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController
        pumukitnewadmin.seriestype:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Seriestype
            classes:
                model: Pumukit\SchemaBundle\Document\SeriesType
                controller: Pumukit\NewAdminBundle\Controller\AdminController
        pumukitnewadmin.link:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Link
            classes:
                model: Pumukit\SchemaBundle\Document\Link
                controller: Pumukit\NewAdminBundle\Controller\LinkController
        pumukitnewadmin.material:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Material
            classes:
                model: Pumukit\SchemaBundle\Document\Material
                controller: Pumukit\NewAdminBundle\Controller\MaterialController
        pumukitnewadmin.track:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Track
            classes:
                model: Pumukit\SchemaBundle\Document\Track
                controller: Pumukit\NewAdminBundle\Controller\TrackController
        pumukitnewadmin.live:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Live
            classes:
                model: Pumukit\LiveBundle\Document\Live
                controller: Pumukit\NewAdminBundle\Controller\LiveController
        pumukitnewadmin.event:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Event
            classes:
                model: Pumukit\LiveBundle\Document\Event
                controller: Pumukit\NewAdminBundle\Controller\EventController
        pumukitnewadmin.eventpic:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Pic
            classes:
                model: Pumukit\LiveBundle\Document\Event
                controller: Pumukit\NewAdminBundle\Controller\EventPicController
        pumukitnewadmin.permissionprofile:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:PermissionProfile
            classes:
                model: Pumukit\SchemaBundle\Document\PermissionProfile
                controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController
        pumukitnewadmin.group:
            driver: doctrine/mongodb-odm
            templates: PumukitNewAdminBundle:Group
            classes:
                model: Pumukit\SchemaBundle\Document\Group
                controller: Pumukit\NewAdminBundle\Controller\GroupController
